/**
 * Terms of Service and Privacy Policy (PRD-04 §3.5). Plain words, and only
 * what the product actually does today — update these when a feature that
 * collects new data ships (resume upload, payments, mentor sessions).
 */

export type LegalSection = { title: string; paragraphs: string[]; points?: string[] };

export type LegalDocument = {
  eyebrow: string;
  title: string;
  description: string;
  updated: string;
  sections: LegalSection[];
};

const contact = "preparationssuccess@gmail.com";

export const terms: LegalDocument = {
  eyebrow: "the fine print",
  title: "Terms of Service",
  description:
    "The rules for using PrepSuccess, written to be read. By creating an account you agree to them.",
  updated: "3 October 2026",
  sections: [
    {
      title: "1. What PrepSuccess is",
      paragraphs: [
        "PrepSuccess helps college students understand how ready they are for placements. An AI onboarding chat learns about you, AI-generated skill checks measure where you stand, and your dashboard shows your readiness, your gaps and what to do next.",
        "PrepSuccess is a preparation tool. It does not guarantee a job, an interview or any placement outcome, and scores on PrepSuccess are not a certification.",
      ],
    },
    {
      title: "2. Your account",
      paragraphs: [
        "You need an account to use the app. Sign up with your email and a password, or with Google.",
      ],
      points: [
        "Give accurate details and keep your password private. You're responsible for what happens under your account.",
        "You must be at least 18, or have the consent of a parent or guardian to use PrepSuccess.",
        "One account per person. Don't create accounts for someone else or share yours.",
        `Tell us at ${contact} if you think someone else has access to your account.`,
      ],
    },
    {
      title: "3. Using the AI features",
      paragraphs: [
        "The onboarding chat, skill checks, practical-task feedback and the coach's take are generated by an AI model. AI can be wrong. Use explanations and feedback as guidance, and check anything important against the learning resources we link to.",
        "AI features are free during the trial period. We limit how many AI requests each account can make per day so the service stays available for everyone, and we may change these limits.",
      ],
    },
    {
      title: "4. Fair use",
      paragraphs: ["Please don't:"],
      points: [
        "Try to get around rate limits, daily AI limits or access controls.",
        "Use automated tools to scrape question pools, answers or other students' data.",
        "Submit content in practical tasks or chats that is illegal, abusive, or someone else's private information.",
        "Interfere with the service, probe it for vulnerabilities without permission, or reverse-engineer it.",
      ],
    },
    {
      title: "5. Content",
      paragraphs: [
        "What you write in chats and task submissions stays yours. You give us permission to store and process it to run PrepSuccess for you — to score your checks, give feedback and build your dashboard.",
        "The questions, explanations, learning-resource lists and the rest of the product belong to PrepSuccess. Links to outside learning resources go to sites we don't control; their own terms apply there.",
      ],
    },
    {
      title: "6. Price",
      paragraphs: [
        "PrepSuccess is free to use today. If we introduce paid features later, we'll tell you before anything is charged, and nothing you already have will be charged for retroactively.",
      ],
    },
    {
      title: "7. Ending your account",
      paragraphs: [
        `You can stop using PrepSuccess at any time. To delete your account and data, email ${contact} from the address you signed up with.`,
        "We may suspend an account that breaks these terms, after telling you why where we reasonably can.",
      ],
    },
    {
      title: "8. Liability",
      paragraphs: [
        "PrepSuccess is provided as is. We work to keep it accurate and available, but we can't promise it will be error-free or always online. To the extent the law allows, we aren't liable for indirect losses, such as a missed opportunity, arising from using the service.",
      ],
    },
    {
      title: "9. Changes and contact",
      paragraphs: [
        "If we change these terms in a way that matters, we'll update the date above and let signed-in users know. These terms are governed by the laws of India.",
        `Questions? Write to ${contact}.`,
      ],
    },
  ],
};

export const privacy: LegalDocument = {
  eyebrow: "your data",
  title: "Privacy Policy",
  description:
    "What we collect, why, who processes it, and what you can ask us to do with it. No selling, no ads.",
  updated: "3 October 2026",
  sections: [
    {
      title: "1. What we collect",
      paragraphs: ["Only what the product needs:"],
      points: [
        "Account details: your name, email address, a hashed password (we never store the password itself) or your Google account ID and profile picture if you sign in with Google.",
        "Your profile: what you tell the onboarding chat — for example your degree, year, college, skills, interests, goals and target role.",
        "Your learning data: skill-check questions and your answers, scores, practical-task submissions and the feedback on them.",
        "AI usage: a record of each AI request (which feature, when, how many tokens, whether it worked). This lets us run the free trial and daily limits fairly.",
        "Technical data: request logs with your IP address and browser details, kept to keep the service secure and fix errors.",
      ],
    },
    {
      title: "2. Why we use it",
      paragraphs: [
        "To run PrepSuccess for you: personalise your checks, score them, show your dashboard and give feedback. To keep accounts secure, prevent abuse and fix problems. And to understand, in aggregate, how the product is used so we can improve it.",
        "We don't sell your data, and we don't show ads.",
      ],
    },
    {
      title: "3. The AI",
      paragraphs: [
        "When you chat, take a check or submit a task, the relevant part of your profile and answers is sent to our AI provider (Google's Gemini API) to generate the reply. We send only what that request needs, and we tell the AI to use only your own data — it can't invent skills or scores for you.",
      ],
    },
    {
      title: "4. Who else processes it",
      paragraphs: ["We use a small number of service providers, each only for its job:"],
      points: [
        "Supabase — hosts our database.",
        "Render and Vercel — host the backend and the website.",
        "Google — Gemini for AI features, Google sign-in if you choose it, and Gmail for sending verification codes.",
        "Error tracking and product analytics tools, if enabled, receive technical data and anonymous usage events — never your answers or chats.",
      ],
    },
    {
      title: "5. Who on our side can see it",
      paragraphs: [
        "Admins see account details needed for support (name, email, role, whether the account is active) and platform-wide totals. The admin tools don't let anyone browse an individual student's answers or results. When mentorship launches, a mentor will see only what a booked session needs.",
      ],
    },
    {
      title: "6. Cookies and storage",
      paragraphs: [
        "We keep your sign-in tokens in your browser's local storage so you stay signed in, and use a short-lived cookie during Google sign-in. We don't use advertising cookies.",
      ],
    },
    {
      title: "7. How long we keep it",
      paragraphs: [
        "We keep your data while your account is active. If you ask us to delete your account, we delete your profile, chats, checks and submissions, keeping only what the law requires us to keep.",
      ],
    },
    {
      title: "8. Your rights",
      paragraphs: [
        `You can see and edit your profile in the app at any time. You can also ask us for a copy of your data, to correct it, or to delete it, by writing to ${contact}. We'll reply within 30 days.`,
      ],
    },
    {
      title: "9. Security",
      paragraphs: [
        "Passwords are hashed with bcrypt, sign-in tokens are short-lived and rotated, traffic is encrypted with HTTPS, and the database is only reachable through our backend. No system is perfectly secure, so if we ever learn of a breach affecting you, we'll tell you.",
      ],
    },
    {
      title: "10. Changes and contact",
      paragraphs: [
        "If we change this policy in a way that matters, we'll update the date above and let signed-in users know.",
        `Questions about your data? Write to ${contact}.`,
      ],
    },
  ],
};
