/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — the process is running */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: {
                                /** @constant */
                                status: "ok";
                            };
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — the database is reachable */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready to serve traffic. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: {
                                /** @constant */
                                status: "ok";
                                /** @constant */
                                database: "ok";
                            };
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `SERVICE_UNAVAILABLE` — database not reachable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/send-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a signup verification code
         * @description Step 1 of signup. Emails a 6-digit code valid for 10 minutes. Only the newest code works. A new code can be requested once every 60 seconds.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SendOtpRequest"];
                };
            };
            responses: {
                /** @description Code sent. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["SendOtpResponse"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `EMAIL_ALREADY_REGISTERED` — log in instead. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `VALIDATION_ERROR` — request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `OTP_RECENTLY_SENT` (60s cooldown) or `TOO_MANY_REQUESTS`. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `EMAIL_SEND_FAILED` — try again. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with the emailed code
         * @description Step 2 of signup. Verifies the OTP (3 attempts), creates the user and their profile, and signs them in.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created and signed in. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["TokenResponse"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `OTP_INVALID`, `OTP_EXPIRED` or `OTP_TOO_MANY_ATTEMPTS`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `EMAIL_ALREADY_REGISTERED`. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `VALIDATION_ERROR` — request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `TOO_MANY_REQUESTS` — rate limit hit; wait a minute. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Signed in. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["TokenResponse"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `INVALID_CREDENTIALS` — same message whether the email or the password is wrong. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `ACCOUNT_DEACTIVATED`. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `VALIDATION_ERROR` — request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `TOO_MANY_REQUESTS` — rate limit hit; wait a minute. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair
         * @description Rotates the refresh token: the one you send is revoked and a new pair is returned. Reusing an already-rotated token signs the user out of every session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New tokens issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["TokenResponse"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `INVALID_REFRESH_TOKEN` — sign in again. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `VALIDATION_ERROR` — request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `TOO_MANY_REQUESTS` — rate limit hit; wait a minute. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Always succeeds, even for an unknown or already-revoked token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Signed out. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["Message"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `VALIDATION_ERROR` — request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["AuthUser"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `UNAUTHORIZED` (no token) or `INVALID_TOKEN` (expired/invalid). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google sign-in (browser redirect)
         * @description Open this URL in the browser (a link, not fetch). Redirects to Google's consent screen. Google then returns to `/api/v1/auth/google/callback`, which redirects to the frontend's `/auth/callback#access_token=…&refresh_token=…&next=…`, or to `/login?error=<code>` on failure.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Same-site path to land on after sign-in. */
                    next?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Google's consent screen. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `TOO_MANY_REQUESTS` — rate limit hit; wait a minute. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `GOOGLE_NOT_CONFIGURED` — Google keys missing on the server. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth callback (called by Google)
         * @description Not called directly. Verifies `state` + PKCE, exchanges the code, then logs in the Google user, links Google to an existing account with the same email, or creates a new account. Error codes sent to `/login?error=`: `google_cancelled`, `google_failed`, `google_session_expired`, `google_email_unverified`, `google_account_conflict`, `account_deactivated`.
         */
        get: {
            parameters: {
                query?: {
                    code?: string;
                    state?: string;
                    error?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the frontend with tokens (URL fragment) or an error code. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my account and profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in user, including `profile`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["AuthUser"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `UNAUTHORIZED` or `INVALID_TOKEN`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update my name and/or profile
         * @description Profile fields are **merged**: fields you don't send are kept (including anything the AI onboarding collected), and `null` clears a field. Unknown fields are rejected.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateMeRequest"];
                };
            };
            responses: {
                /** @description The updated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["AuthUser"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `UNAUTHORIZED` or `INVALID_TOKEN`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `VALIDATION_ERROR` — request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description `TOO_MANY_REQUESTS` — rate limit hit; wait a minute. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My AI free-trial and daily usage
         * @description AI is free during a trial that starts at signup. Every AI call is metered; the daily limit protects the shared free-tier quota and resets at midnight IST.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trial and quota status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            success: true;
                            data: components["schemas"]["AiStatus"];
                            /**
                             * Format: uuid
                             * @description Echoes the X-Request-ID response header.
                             */
                            request_id: string;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description `UNAUTHORIZED` or `INVALID_TOKEN`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SendOtpRequest: {
            /**
             * @description Trimmed and lowercased before use.
             * @example asha@college.edu
             */
            email: string;
        };
        RegisterRequest: {
            /** @example Asha */
            first_name: string;
            /** @example Verma */
            last_name?: string;
            /**
             * @description Trimmed and lowercased before use.
             * @example asha@college.edu
             */
            email: string;
            /** @example correct-horse-battery */
            password: string;
            /**
             * @description Stored in the user's profile.
             * @example 3
             */
            student_year?: number;
            /**
             * @description Code emailed by /auth/send-otp.
             * @example 482913
             */
            otp: string;
        };
        LoginRequest: {
            /**
             * @description Trimmed and lowercased before use.
             * @example asha@college.edu
             */
            email: string;
            /** @example correct-horse-battery */
            password: string;
        };
        RefreshRequest: {
            /** @description Opaque refresh token from login/register/refresh. */
            refresh_token: string;
        };
        /** @description Partial update. Profile fields are merged into the existing profile: omitted fields are kept, `null` clears one. */
        UpdateMeRequest: {
            /** @example Asha */
            first_name?: string;
            /** @example Verma */
            last_name?: string | null;
            profile?: components["schemas"]["ProfilePatch"];
        };
        ProfilePatch: {
            college?: string | null;
            degree?: string | null;
            branch?: string | null;
            student_year?: number | null;
            graduation_year?: number | null;
            target_role?: string | null;
            mobile_no?: string | null;
            age?: number | null;
            gender?: ("male" | "female" | "other" | "prefer_not_to_say") | null;
            location?: string | null;
            skills?: string[] | null;
            interests?: string[] | null;
            goals?: string[] | null;
            experience?: string | null;
        };
        ErrorResponse: {
            /** @constant */
            success: false;
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example Request validation failed. */
                message: string;
                /** @description Validation issues, when relevant. */
                details: unknown[];
            };
            /**
             * Format: uuid
             * @description Echoes the X-Request-ID response header.
             */
            request_id: string;
            /** Format: date-time */
            timestamp: string;
        };
        SendOtpResponse: {
            /** @example We sent a 6-digit code to asha@college.edu. */
            message: string;
            /** @example asha@college.edu */
            email: string;
        };
        TokenResponse: {
            /** @description JWT. Send as `Authorization: Bearer <token>`. */
            access_token: string;
            /** @description Opaque refresh token from login/register/refresh. */
            refresh_token: string;
            /** @constant */
            token_type: "bearer";
            /**
             * @description Access token lifetime in seconds.
             * @example 1800
             */
            expires_in: number;
            user: components["schemas"]["AuthUser"];
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** @example Asha */
            first_name: string;
            /** @example Verma */
            last_name: string | null;
            /** @example asha@college.edu */
            email: string;
            profile_image_url: string | null;
            /** @enum {string} */
            role: "student" | "mentor" | "admin";
            /** @enum {string} */
            auth_provider: "local" | "google";
            is_verified: boolean;
            /** @description True once the AI onboarding has finished. */
            onboarding_completed: boolean;
            /**
             * @description Schemaless profile collected by the AI onboarding (user_profiles.profile_data).
             * @example {
             *       "student_year": 3
             *     }
             */
            profile: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Message: {
            /** @example Signed out. */
            message: string;
        };
        AiStatus: {
            /** @description False when AI isn't configured on the server. */
            available: boolean;
            /** @description Whether this user can make an AI request right now. */
            allowed: boolean;
            /** @description Why `allowed` is false. */
            reason: ("AI_NOT_CONFIGURED" | "AI_TRIAL_ENDED" | "AI_DAILY_LIMIT") | null;
            trial: {
                active: boolean;
                /** Format: date-time */
                ends_at: string;
                /** @example 87 */
                days_left: number;
                /** @description While false, an ended trial is shown but doesn't block AI. */
                enforced: boolean;
            };
            today: {
                /** @example 12 */
                requests: number;
                /** @example 200 */
                limit: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
